---
version: "3"
services:
  postgres:
    image: postgres
    container_name: findpostgres
    restart: always
    ports:
      - 5432:5432

    environment:
      POSTGRES_PASSWORD: mysecretpassword
